lockate_site_homepage:
    path:     /
    defaults: { _controller: SiteBundle:Site:index }

lockate_site_logged:
    path: /site
    defaults: { _controller: SiteBundle:Site:inside }

lockate_site_datareceiver:
    path: /site/v1/datareceiver
    defaults: { _controller: SiteBundle:Site:dataReceiver }
    methods: [POST]
